### ISSUE TITLE
[Sandboxie] Update licenseurl for Classic and Plus packages

### ISSUE THREAD

**Issue by isaak654** [jack1142/choco-auto#11]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

* **What is the current behavior?**

`licenseUrl` fields for Sandboxie Classic and Plus should be updated, because the license names have recently been modified.

Sandboxie Classic license: https://raw.githubusercontent.com/sandboxie-plus/Sandboxie/master/LICENSE.Classic
Sandboxie Plus license: https://raw.githubusercontent.com/sandboxie-plus/Sandboxie/master/LICENSE.Plus

* **What is the expected behavior?**

Update `licenseUrl` fields for Sandboxie Classic and Plus.

**Comment by Jackenmen** [comment]
Thanks for making the issue (+ the email to maintainers), I completely missed the notifications about failed verification testing since they don't really stand out in comparison to notifications about passed verification :smile: 

I updated the license URLs (https://github.com/Jackenmen/choco-auto/commit/e400fce871c90de2d2dca0073de250aec09ac82c) + uploaded a rebuild of 5.67.4/1.12.4 (https://github.com/Jackenmen/choco-auto/commit/33cc87fea122861c6138e68108ad4f286cec7dbb) *and* 5.67.5/1.12.5 (https://github.com/Jackenmen/choco-auto/commit/49ae3ae0d53a9b1cc94737f49232b41d8c13d618, https://github.com/Jackenmen/choco-auto/commit/4b6ff8cb25b0b2afb2d2d5480ef199329016470b) with those changes so it should hopefully get auto-resolved once the packages run through the automated verification. I'll monitor if everything goes as expected, thanks again for the report!

**Comment by Jackenmen** [comment]
> uploaded a rebuild of 5.67.4/1.12.4 ([33cc87f](https://github.com/Jackenmen/choco-auto/commit/33cc87fea122861c6138e68108ad4f286cec7dbb))

That one was uploaded without involving AU so turns out that it didn't build it with the embedded installers and will most definitely fail. 5.67.5 and 1.12.5 builds should go through without issues though, I'll just self-reject the 5.67.4 and 1.12.4 versions on Chocolatey later.

**Comment by isaak654** [comment]
1.12.4 / 5.67.4 builds were defective due to a major regression and even downgraded as pre-release, so it's no big deal.

**Comment by isaak654** [comment]
1.12.4 / 5.67.4 builds were defective due to a bug with Chromium browsers and even downgraded as pre-release, so it's no big deal.

**Comment by Jackenmen** [comment]
Alright, 1.12.5/5.67.5 versions of the packages are now approved and I've self-rejected 1.12.4/5.67.4.
